name: build

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [ 2.7, 2.6, 2.5, head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        sudo apt install tk tk-dev
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: rake compile
